package plugin.customcooking.functions.jade;

public enum LeaderboardType {
    ALL_TIME,
    POSITIVE_ONLY,
    FARMING_ALL_TIME,
    FARMING_MONTHLY,
    FARMING_WEEKLY,
    COOKING_ALL_TIME,
    COOKING_MONTHLY,
    COOKING_WEEKLY,
    BREWING_ALL_TIME,
    BREWING_MONTHLY,
    BREWING_WEEKLY,
    FISHING_ALL_TIME,
    FISHING_MONTHLY,
    FISHING_WEEKLY,
}
