package plugin.customcooking.functions.jade;

public enum LeaderboardType {
    ALLTIME,
    POSITIVEONLY,
    FARMINGALL,
    FARMINGMONTHLY,
    FARMINGWEEKLY,
    COOKINGALL,
    COOKINGMONTHLY,
    COOKINGWEEKLY,
    BREWINGALL,
    BREWINGMONTHLY,
    BREWINGWEEKLY,
    FISHINGALL,
    FISHINGMONTHLY,
    FISHINGWEEKLY,
}
