name: BorealCore
version: '${project.version}'
main: plugin.customcooking.BorealCore
author: [ SnowyOwl217 ]
api-version: 1.18
depend:
  - ProtocolLib
  - PlaceholderAPI
  - NBTAPI
  - ItemsAdder
  - CustomCrops
  - CustomFishing
softdepend:
  - DecentHolograms
  - DiscordSRV
  - Duels

commands:
  cooking:
    description: The command to manage CustomCooking
  jade:
    description: The command to manage Jade
  kn:
    description: The command to manage Nodes
  wiki:
    description: The command to manage the Wiki
  plushies:
    description: The command to manage the Gamble feature

permissions:
  customcooking.*:
    default: false
  customcooking.admin:
    default: op