name: CustomCooking
version: '${project.version}'
main: plugin.customcooking.CustomCooking
author: [ SnowyOwl217 ]
api-version: 1.18
depend:
  - ProtocolLib
  - PlaceholderAPI
  - NBTAPI
  - ItemsAdder
softdepend:
  - DecentHolograms

commands:
  cooking:
    description: The main plugin command
  jade:
    description: The command to manage Jade
  kn:
    description: The command to manage Nodes
  wiki:
    description: The command to manage the Wiki

permissions:
  customcooking.*:
    default: false
  customcooking.admin:
    default: op